import turtle

# List of Color ["violet", "indigo", "blue", "green", "yellow", "orange", "red"]
# setting
turtle.speed(10)
turtle.width(3)
turtle.bgcolor("black")

#vatiables
size = 50
r = 500
degree = 20
#draw circle
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("violet")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("indigo")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("blue")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("green")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("yellow")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("orange")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("red")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("violet")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("indigo")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("blue")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("green")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("yellow")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("orange")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("red")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("violet")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("indigo")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("blue")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("green")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("yellow")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("orange")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("red")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("violet")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("indigo")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("blue")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("green")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("yellow")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("orange")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("red")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("violet")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("indigo")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("blue")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("green")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("yellow")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("orange")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("red")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("violet")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("indigo")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("blue")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("green")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("yellow")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("orange")
turtle.right(90)
turtle.circle(size)
turtle.penup()
turtle.circle(r, degree)
turtle.pendown()
turtle.color("red")
turtle.right(90)
turtle.circle(size)

turtle.mainloop()
